plugins: 
- jekyll-seo-tag
title: Trans Scandinavia
tagline: A community network for trans and non-binary folks with ties to Scandinavia. Find us on Discord!
description: A community network for trans and non-binary folks with ties to Scandinavia. Find us on Discord!
image: 
  path: /images/pic00.jpg
  height: 100
  width: 100